title: Benard Adewole
logo: /assets/img/headshot_circle.png
description: I'm a master's student in Robotics at the University of Michigan, specializing in autonomy and robot perception.
show_downloads: false
theme: jekyll-theme-minimal
